### ISSUE TITLE
Git tag for v1.0 is missing

### ISSUE THREAD

**Issue by merkys** [mjoldfield/pi-tm1638#3]
According to the README file, version 1.0 has been released. It would be convenient to have this version also tagged in Git.

**Comment by mjoldfield** [comment]
I've added a tag, but I'm not sure if I've done it correctly: please could you let me know.

M.

**Comment by merkys** [comment]
The tag seems fine, thanks a lot for prompt response!

There seem to be minor differences between the contents of GitHub repository and the source tarball from https://github.com/downloads/mjoldfield/pi-tm1638/pi-tm1638-1.0.tar.gz, but these are mostly `aclocal`-generated stuff, not code, so that's fine, I suppose.
